"""mantenimiento table

Revision ID: a75787b2529f
Revises: 
Create Date: 2019-10-01 16:51:12.052343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a75787b2529f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mantenimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kilometraje', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('valor_mano_obra', sa.Integer(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mantenimiento_fecha_hora'), 'mantenimiento', ['fecha_hora'], unique=False)
    op.create_index(op.f('ix_mantenimiento_kilometraje'), 'mantenimiento', ['kilometraje'], unique=False)
    op.create_table('repuesto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=120), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repuesto_fecha_hora'), 'repuesto', ['fecha_hora'], unique=False)
    op.create_index(op.f('ix_repuesto_marca'), 'repuesto', ['marca'], unique=False)
    op.create_index(op.f('ix_repuesto_nombre'), 'repuesto', ['nombre'], unique=False)
    op.create_table('cambio_partes',
    sa.Column('mantenimiento_id', sa.Integer(), nullable=True),
    sa.Column('repuesto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mantenimiento_id'], ['mantenimiento.id'], ),
    sa.ForeignKeyConstraint(['repuesto_id'], ['repuesto.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cambio_partes')
    op.drop_index(op.f('ix_repuesto_nombre'), table_name='repuesto')
    op.drop_index(op.f('ix_repuesto_marca'), table_name='repuesto')
    op.drop_index(op.f('ix_repuesto_fecha_hora'), table_name='repuesto')
    op.drop_table('repuesto')
    op.drop_index(op.f('ix_mantenimiento_kilometraje'), table_name='mantenimiento')
    op.drop_index(op.f('ix_mantenimiento_fecha_hora'), table_name='mantenimiento')
    op.drop_table('mantenimiento')
    # ### end Alembic commands ###
